const createComment = require('./createComment.js');
const dislcaimer = [
  'This file was auto generated by Galileo at Bitso\n',
  'DO NOT edit directly',
  `Last Generated: ${new Date()}\n`,
];
exports.DISCLAIMER = {

  js: createComment(dislcaimer, 'js'),
};
