// This file was auto generated by Galileo at Bitso
  
// DO NOT edit directly  
// Last Generated: Sun Oct 10 2021 18:21:48 GMT-0500 (Central Daylight Time)
  

//Universe Typing
interface UniverseColor {
	readonly 0?: string
	readonly 10: string
	readonly 20: string
	readonly 30: string
	readonly 40: string
	readonly 50: string
	readonly 60: string
	readonly 70: string
	readonly 80: string
	readonly 90: string
	readonly 100: string
}
export const moonlight : UniverseColor;
export const stardust : UniverseColor;
export const borealis : UniverseColor;
export const earth : UniverseColor;
export const nebula : UniverseColor;
export const mars : UniverseColor;