// This file was auto generated by Galileo at Bitso
  
// DO NOT edit directly  
// Last Generated: Sun Oct 10 2021 18:21:48 GMT-0500 (Central Daylight Time)
  

// Universe
// Figma: https://www.figma.com/file/XU1kwGVYTHQ21HJiYpYSDQ/Moon-Foundation?node-id=129%3A2873
// Documentation: https://bitsomx.atlassian.net/wiki/spaces/~423496812/pages/3115942202  

export const moonlight = Object.freeze({
	0:'#FFFFFF', 
	10:'#F8F9FC', 
	20:'#EEF0F7', 
	30:'#D1D8DF', 
	40:'#AFBCC6', 
	50:'#81919C', 
	60:'#63727C', 
	70:'#4A5760', 
	80:'#333C42', 
	90:'#191E23', 
	100:'#0C0F12', 
});
export const stardust = Object.freeze({
	10:'#FFF9E4', 
	20:'#FFF1C1', 
	30:'#FFE99E', 
	40:'#FCD963', 
	50:'#F8CA2D', 
	60:'#F2BB00', 
	70:'#DAA800', 
	80:'#B58B00', 
	90:'#876800', 
	100:'#5D4700', 
});
export const borealis = Object.freeze({
	10:'#F2FFEE', 
	20:'#CFFAC2', 
	30:'#B5F4A2', 
	40:'#8DDD74', 
	50:'#68C74A', 
	60:'#29AC00', 
	70:'#098300', 
	80:'#196700', 
	90:'#104500', 
	100:'#112D0C', 
});
export const earth = Object.freeze({
	10:'#E5EDFF', 
	20:'#BCD4FF', 
	30:'#8FB4FF', 
	40:'#78A0FF', 
	50:'#437EFF', 
	60:'#2969FF', 
	70:'#1954E0', 
	80:'#0F43BC', 
	90:'#093394', 
	100:'#06246B', 
});
export const nebula = Object.freeze({
	10:'#F3E6FF', 
	20:'#E5C5FF', 
	30:'#D9AAFF', 
	40:'#C27AFF', 
	50:'#AB4FFF', 
	60:'#7B0AF3', 
	70:'#710DD7', 
	80:'#620FB6', 
	90:'#561599', 
	100:'#330561', 
});
export const mars = Object.freeze({
	10:'#FFECEE', 
	20:'#FFD1D6', 
	30:'#FFB5BD', 
	40:'#FF8492', 
	50:'#FD596B', 
	60:'#EA172F', 
	70:'#D11328', 
	80:'#B21324', 
	90:'#8F1320', 
	100:'#6B121B', 
});